### ISSUE TITLE
Project is giving error while installing for sementic-ui

### ISSUE THREAD

**Issue by Aman290** [catalogicsoftware/ngx-dynamic-dashboard-framework#27]
Error: ENOENT: no such file or directory, open '/home/brain/Downloads/ngx-dynamic-dashboard-framework-master/node_modules/semantic-ui/dist/semantic.min.js'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)

As I have cloned the project and running it, but it is giving error while installing or serving the application.
Can anyone help me in this?

**Comment by jayhamilton** [comment]
Are you prompted to install Semantic UI? In other words, when you do npm install, at some point do you get prompted to answer questions regarding Semantic-UI?

**Comment by jayhamilton** [comment]
See if what you are facing is related to another semantic-ui issue: https://github.com/catalogicsoftware/ngx-dynamic-dashboard-framework/issues/25
